sudo: false
dist: trusty

language: php

php:
    - 7.1
    - 7.2
    - nightly

git:
    depth: 1

env:
    global:
        - CC="ccache gcc"
        - PHALCON_VERSION=v3.4.0

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

cache:
    apt: true
    timeout: 604800
    directories:
        - $HOME/.composer/cache
        - $HOME/pear
        - $HOME/.local/lib

before_install:
    - ulimit -c unlimited -S || true
    - phpenv config-rm xdebug.ini || true
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com $GH_TOKEN; fi;

install:
    - bash tests/ci/install_phalcon.sh
    - echo 'extension=memcached.so' > $(phpenv root)/versions/$(phpenv version-name)/etc/conf.d/50-memcached.ini
    - |
        composer install \
            --ignore-platform-reqs \
            --prefer-dist \
            --no-interaction \
            --no-ansi \
            --no-progress \
            --optimize-autoloader \
            --no-suggest
    - ls -al `$(phpenv which php-config) --extension-dir`
    - $(phpenv which php) -v
    - $(phpenv which php) -m
    - $(phpenv which php) --ri phalcon
    - echo 'SHOW VARIABLES LIKE "%version%"' | mysql -u root

before_script:
    - echo 'CREATE DATABASE phosphorum CHARSET=utf8 COLLATE=utf8_unicode_ci' | mysql -u root
    - echo "CREATE USER 'phosphorum'@'%' IDENTIFIED BY 'secret'" | mysql -u root
    - echo "GRANT ALL PRIVILEGES ON phosphorum.* TO 'phosphorum'@'%' WITH GRANT OPTION" | mysql -u root
    - cat schemas/forum.sql | mysql -u root phosphorum
    - cp ./tests/.env.travis .env
    - php -S 127.0.0.1:8000 -t public/ .htrouter.php >/dev/null 2>&1 &

script:
    - vendor/bin/phpcs
    - vendor/bin/phpstan analyse -l max modules
#    - vendor/bin/codecept build
#    - vendor/bin/codecept run unit
#    - vendor/bin/codecept run console
#    - vendor/bin/codecept run functional
#    - vendor/bin/codecept run acceptance

after_failure:
    - for file in `ls ./tests/_output`; do [ -f ./tests/_output/$file ] && cat ./tests/_output/$file; done;

after_success:
    - if [[ ! -z "${CODECOV_TOKEN}" ]]; then bash <(curl -s https://codecov.io/bash); fi;

notifications:
    email:
        on_success: never
        on_failure: never

addons:
    hosts:
        - pforum.loc
